# Generated by Django 2.2.4 on 2019-08-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['number']},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'number')},
        ),
    ]
