# Generated by Django 2.2.4 on 2019-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190811_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='rock', max_length=50, verbose_name='Gênero'),
            preserve_default=False,
        ),
    ]
