# Generated by Django 2.2.4 on 2019-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='size',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.TimeField(default='00:00', verbose_name='Duração'),
            preserve_default=False,
        ),
    ]
